### ISSUE TITLE
Invoke-ZLocation doesn't work with oh-my-posh + posh-git + ZLocation

### ISSUE THREAD

**Issue by glenncarr** [vors/ZLocation#122]
`Invoke-ZLocation` doesn't save paths when `Set-PoshPrompt` is included in my profile:

My pwsh 7.1.3 $PROFILE:
```
Set-PSReadLineOption -Colors @{ String="Cyan"; Parameter="Green"; Comment="Magenta" }
Set-PSReadLineOption -HistoryNoDuplicates
Set-PSReadlineKeyHandler -Key ctrl+d -Function ViExit

Import-Module posh-git
$env:POSH_GIT_ENABLED = $true
Set-PoshPrompt -Theme '~\Documents\.oh-my-posh.omp.json'

Import-Module ZLocation
```
Reading the [Note](https://github.com/vors/ZLocation#note) I was hoping simply putting `Import-Module ZLocation` would resolve it.  Removing `Set-PoshPrompt` allows `Invoke-ZLocation` to work correctly.

What am I missing or not understanding?

Thanks.

**Comment by glenncarr** [comment]
Resolved... I had an extra `Import-Module ZLocation` in my `$PROFILE.AllUsersCurrentHost`.  Removing that fixed it.

Sorry about that.

**Comment by MisinformedDNA** [comment]
The order of commands was my problem. Thanks.
