### ISSUE TITLE
Alias for Set-ZLocation does not provide tab completion

### ISSUE THREAD

**Issue by Kethku** [vors/ZLocation#16]
I like to alias Set-ZLocation with j instead of z because then it is on the home row and is easier to press as apposed to z which requires a pinkie contortion to achieve. However aliasing with j to Set-ZLocation does not work as the tab completion does not execute properly.

**Comment by vors** [comment]
Yes, tab-completion implemented hacky. As a workaround, you can modify https://github.com/vors/ZLocation/blob/master/ZLocation/ZLocation.psm1#L95 , but it would be good to have a generic approach, possible with https://github.com/lzybkr/TabExpansionPlusPlus as a dependency from PSGallery.

Thank you for your interest and contributions!
