### ISSUE TITLE
Z Should prioritize the beginning of a foldername

### ISSUE THREAD

**Issue by jjmartin** [vors/ZLocation#26]
i have a folder that i was spending a lot of time in called 
C:\blah\blah\billing-warehouse-microservice

i have another folder callled C:\blah\blah\reload scripts

if i do `z re`  or even `z r`
it should priorize the reload scripts folder IMO over the other folder where it is finding `re` in the middle of the waREhouse.  Even tho i was spending more time in that folder.

(jump-location seemed to do this)

**Comment by vors** [comment]
Hm, good call!
Sorry for not looking at it for years
