### ISSUE TITLE
Fails on first import

### ISSUE THREAD

**Issue by juneb** [vors/ZLocation#27]
When I install and then import the module, I get an error message. 

PSVersion: 5.0.11082.1000
Windows 10 Pro x64

PS C:> ipmo ZLocation
WARNING: ZLocation Pipe become broken :( ZLocation is now self-disabled.
You need to restart all PowerShell instances to re-enable ZLocation.
Please continue your work and do it, when convinient.
You can report the problem on https://github.com/vors/ZLocation/issues.

**Comment by vors** [comment]
Hi June!

Sorry, missed your issues. I was on vacation.
I will take a look.

**Comment by vors** [comment]
Should be fixed after switch to LiteDB
