### ISSUE TITLE
Warning message is misspelled and grammatically incorrect.

### ISSUE THREAD

**Issue by juneb** [vors/ZLocation#28]
PS C:> ipmo ZLocation
WARNING: ZLocation Pipe become broken :( ZLocation is now self-disabled.
You need to restart all PowerShell instances to re-enable ZLocation.
Please continue your work and do it, when convinient.
You can report the problem on https://github.com/vors/ZLocation/issues

Should be:
WARNING: Because ZLocation pipe broke, ZLocation disabled itself. To re-enable ZLocation, restart all PowerShell instances. You can continue your work and do it when convenient. To report the problem, use https://github.com/vors/ZLocation/issues.

**Comment by vors** [comment]
Thank you for working on my English :)

**Comment by vors** [comment]
Should be fixed after switch to LiteDB
