### ISSUE TITLE
CoreCLR / unix port

### ISSUE THREAD

**Issue by vors** [vors/ZLocation#32]
Can we make it work on CoreCLR / unix?

**Comment by cspotcode** [comment]
I took a quick look at the code.  Is the issue with using a Windows named pipe?
  Could the `System.ServiceModel.NetNamedPipeBinding` be replaced with a TCP binding that uses a unix socket?  Or am I oversimplifying the problem?

I just installed this, by the way, after using Jump.Location and hitting bugs.  Thanks for the useful module!

**Comment by vors** [comment]
@cspotcode thank you for the kind words! You are absolutely right, that's pretty much the only platform-specific API used. Named pipe provides the ability to pass .net objects unlike the socket, but it's ok: the protocol is very simple and can be rewritten to use plain text (maybe just use json for serialization).

I really miss this capabilities on macOS where I currently spend most of my time. Would be great to tackle this problem finally.

**Comment by cspotcode** [comment]
I started working on a fix for this.  It ended up being more complicated than I expected because .net core is missing lots of features, and I still need to fix failing tests and crashes.

**Comment by vors** [comment]
@cspotcode awesome!
I will take a look later today.

**Comment by nohwnd** [comment]
@vors Why do we need the pipe? Is that for storage that's accessible by multiple instances? In that case couldn't we just replace it with a file in a known location, a bit of locking and spin waiting? For 10000 items (number and path), serializing as json and storing by set-content I am getting 922 ms for save and 154 ms for read (which admitedly is a lot), but for 1000 paths it's 100 ms and 18 ms, which is still much slower than concurrent dictionary, but imho good enough for human interaction. Personally I have about  100 paths in zlocation (it keeps deleting all of them regularly), and there we talk about 32 ms and 3 ms. We can also cache the data and only reload when the file changes (checking LastWriteTime takes 1ms).

**Comment by vors** [comment]
@nohwnd you just described how it works in https://github.com/tkellogg/Jump-Location :)
the whole reason to create a different project was my failure to synchronize everything thru the file and a never-ending stream of bugs that raised from it.
I don't say that it's not possible, it's just not easy and seems like a wrong hammer imo.

**Comment by nohwnd** [comment]
@vors gotcha. I was also thinking about using [liteDb](https://github.com/mbdavid/LiteDB/releases) for the storage, which would remove the need for writing custom synchronization code, but the api is difficult to use from PowerShell directly, and it would add hefty 126 kb to the module. Also the version 4 does not seem to work with PowerShell.

**Comment by vors** [comment]
DB is a good option, I would totally tolerate 126kb.
Maybe this is actually a much better option. thank you for pointing that out!

**Comment by cspotcode** [comment]
I was kicking around the idea of using SqLite.  It's bigger (about 400kb) and there don't appear to be any straightforward bindings for dotnet core.  LiteDB sounds like a perfect alternative as long as it has robust synchronization on the DB file like SQLite.

**Comment by nohwnd** [comment]
Seems to work pretty fine (tested on posh 5.1.15063), with litedb4 two instances of powershell accessing it:
```powershell
Import-Module "C:\Users\jares\source\repos\LiteDbWrapper\ZLocation\bin\Debug\ZLocation.dll"
$db = [ZLocation.Db]::new("C:\temp\abc.db")
$db.GetAll()

$path = $pwd.Path
$db.Insert($path, 1)
$db.Upsert($path, 2)
$db.Update($path, 3)
$db.Get($path)
$db.Delete($path)
```
```txt
Path           Score
----           -----
a                  2
b                  1
bc                 1
C:\Users\jares     3
```
[LiteDbWrapper.zip](https://github.com/vors/ZLocation/files/1413572/LiteDbWrapper.zip)

**Comment by vors** [comment]
@cspotcode did a kick-ass job implementing it 🎉
