### ISSUE TITLE
[wish-list] list histories when running z without args and test match when using 'z -l'

### ISSUE THREAD

**Issue by skywind3000** [vors/ZLocation#41]
Having been using rupa's famous [z.sh](https://github.com/rupa/z) under linux for years, thanks for ZLocation, because I can use the same z on Windows now.

It is very convenience if ZLocation could support two more z.sh's feature:

1. list path history and priority when calling z without parameters:

![z-1](https://user-images.githubusercontent.com/3035071/35395077-4d8f14fe-0224-11e8-8683-eb8c4e9aa346.png)

very handy to see what in my history.

2. test match with `z -l <key1> [key2, key3, ...]`:

![z-4](https://user-images.githubusercontent.com/3035071/35395174-97c93aae-0224-11e8-8ad4-053c8f07a988.png)

People using z sometimes got confused what path will be matched with they keywords.
Then they have a `z -l` command to test they keywords before jumping if they are not so sure.

`z -l <key1> [key2, key3, ...]` is a very high frequency command in my everyday workflow.

---
Is it possible to add these two features in ZLocation ?? If so, working with ZLocation will be much more productive.

**Comment by theaquamarine** [comment]
`Get-ZLocation` lists the known locations, though it doesn't have a search feature like that. It would probably be added quite simple to add, since that's pretty much what [the tab expansion does](https://github.com/vors/ZLocation/blob/master/ZLocation/ZLocation.psm1#L98) at the moment with `Get-Zlocation` and `Find-Matches`.

**Comment by vors** [comment]
Good call - probably should make `z` it's own function that would support both listing and jumping.

**Comment by vors** [comment]
Thank you for the suggestion, merged fix for it in #53!
