### ISSUE TITLE
Incorrect profile script written by oneliner installation

### ISSUE THREAD

**Issue by Bouke** [vors/ZLocation#44]
Running the oneliner from the readme resulted in the following `profile.ps1`:

![screen shot 2018-03-29 at 14 15 52](https://user-images.githubusercontent.com/235882/38088328-b915f248-335b-11e8-8b6d-a0e141b2c3c0.png)

Does the oneliner maybe expect the file to be in UTF-16 encoding?

**Comment by vors** [comment]
What's your PS version?

**Comment by Bouke** [comment]
```
 $PSVersionTable.PSVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      16299  251
```

**Comment by vors** [comment]
Hm, yes I think you right: PS redirection just uses UTF16.
Can you, please, open an issue in https://github.com/PowerShell/PowerShell with a small repro about it?

Does `Add-Content -Path ... -Value ...` handles it more intelligent? (I don't have a windows machine handy to try it out)

**Comment by walliski** [comment]
+1 for this. Should change the readme or use another way of inserting text...

**Comment by vors** [comment]
Ok, I tried to improve it. Let me know if that doesn't worth either.
