### ISSUE TITLE
Doesn't work with Cmder

### ISSUE THREAD

**Issue by michaeljones32** [vors/ZLocation#45]
Installed successfully and works with regular powershell, but when using cmder I get this error:
```
Cannot write to function prompt because it is read-only or constant.
At C:\Users\MJ2\Documents\WindowsPowerShell\Modules\ZLocation\0.3.0\ZLocation.psm1:56 char:9
+         $function:prompt = [ScriptBlock]::Create($newPrompt)
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (prompt:String) [], SessionStateUnauthorizedAccessException
    + FullyQualifiedErrorId : FunctionNotWritable
```

**Comment by vors** [comment]
hm, interesting, why cmder makes the promp function RO?

**Comment by michaeljones32** [comment]
What is RO?

I was just running z and it threw that, just running standard cmder, never had any issues like this before

**Comment by Kethku** [comment]
RO stands for read only.

**Comment by vors** [comment]
I don't have a windows machine at the moment, if anybody can investigate and confirm this isssue, I'd very much appreciate it.

**Comment by Snaptags** [comment]
Yes, I can confirm this. But as far as I am concerned this is a cmder problem. Handling the prompt itself is one of its main features:
> …and a custom prompt layout.
https://github.com/cmderdev/cmder
Zlocation is working perfectly using conemu under windows, which is what cmder is based on.

But why does ZLocation HAVE to access the prompt anyways? I never see any impact on my prompt :)

**Comment by vors** [comment]
Hm, looks like they left `PrePrompt` / `PostPrompt` function for customization. It's probably easier to special-case cmder prompt (i.e. catch the error while changing prompt) and use one of this functions instead.

https://github.com/cmderdev/cmder/blob/4655888690cd807cd24b082509c1e65e0a4cca38/vendor/profile.ps1#L175

**Comment by cspotcode** [comment]
#48 offers a solution.

```
# In your profile:
Import-Module ZLocation -ArgumentList @{Register = $false}
Function PrePrompt {
    Update-ZLocation
}
```

**Comment by vors** [comment]
@cspotcode thank you for looking at it!
I think we can make UX here more seamless by special-casing cmder and handling it transparently for people.

**Comment by glucas** [comment]
@cspotcode Thanks, your PR works great for me. Here's the snippet I've got working in my cmder user-profile.ps1 (note the $pwd is important!):

`[ScriptBlock]$PrePrompt = {
    Update-ZLocation $pwd
}
`

**Comment by vors** [comment]
Hm, actually it was easier than I though: hint to use `-Force` was below https://github.com/cmderdev/cmder/blob/4655888690cd807cd24b082509c1e65e0a4cca38/vendor/profile.ps1#L211

**Comment by vors** [comment]
Fixed
