### ISSUE TITLE
new ZLocation service fails on WindowsPowerShell

### ISSUE THREAD

**Issue by cspotcode** [vors/ZLocation#55]
This is my fault.  I'm checking `$IsMacOS` even though that variable is not set on WindowsPowerShell.  Should be an easy fix.

https://github.com/vors/ZLocation/blob/master/ZLocation/ZLocation.Service.psm1#L54

**Comment by vors** [comment]
Fixed in #52

**Comment by HeedfulCrayon** [comment]
So this still causes an error to be added to `$global:error` which causes the `$lastCommandFailed` to be true in [oh-my-posh](https://github.com/JanDeDobbeleer/oh-my-posh)
![Annotation 2019-05-17 113920](https://user-images.githubusercontent.com/5224972/57945995-7ed8a480-7898-11e9-8416-108de0b59547.png)

**Comment by cspotcode** [comment]
That's annoying; how do we check for a variable without generating any sort
of error?  Can we try-catch around that command?

**Comment by vors** [comment]
Man, that's indeed annoying.

I think `-ErrorAction Ignore` is doing the same and doesn't add to the `$error`.

**Comment by theaquamarine** [comment]
`-ErrorAction Ignore` is what's in Master now - this was solved in #75, https://github.com/vors/ZLocation/blob/9b3b74cd5fbd924209bf2688ff33d3da076b8bcf/ZLocation/ZLocation.Service.psm1#L61

`-ErrorAction Ignore` or just `if ($IsMacOS)` will both avoid adding to `$error`, I'm not really sure of the appeal of `Get-Variable` there, to be honest.

**Comment by cspotcode** [comment]
I don't remember exactly, but I think Get-Variable is used to avoid a
strict mode error for undefined variables.

**Comment by theaquamarine** [comment]
Ah, yeah, that makes sense. Thanks!

**Comment by HeedfulCrayon** [comment]
I guess mine is just out of date. In the picture it shows `-erroraction silentlycontinue`. I will update mine and report back, sounds like it isn't an issue

**Comment by HeedfulCrayon** [comment]
For some reason my powershellget is not updating the module. I will have to investigate that further, however I have found that the variables `IsWindows` and `IsMacOS` are for powershell core only.  If you want it compatible with the windows version of powershell, there could be some logic built around the different versions to avoid the errors instead of just ignoring them. Otherwise I might suggest stating that this module only works in powershell core

**Comment by cspotcode** [comment]
That's why we use `Get-Variable` and suppress the errors, because we know
those variables are only declared on Powershell Core.

**Comment by vors** [comment]
> For some reason my powershellget is not updating the module

Sorry - it was not published. Just did it, so the fix is available in PSGallery in 1.2.0
