### ISSUE TITLE
Hide z-location.db on Unix

### ISSUE THREAD

**Issue by swsnr** [vors/ZLocation#57]
Hello,

now that zlocation supports powershell core I tried it macOS; works fine so far but I noticed a minor nuisance:

ZLocation puts its database to `$HOME/zlocation.db`, ie, a visible file.  The file appears in `ls` or in Finder (=macos explorer) windows.  

On Unix, data files of this kind are normally created as hidden files, with a leading dot: `$HOME/.zlocation.db`.  

Would it be possible to move the database to this place on Unix, so that it doesn't clutter my `$HOME` directory?

**Comment by vors** [comment]
Yes, that's a reasonable.

**Comment by cspotcode** [comment]
For easy backwards compatibility, it can check for the presence of both "$HOME/zlocation.db" and "$HOME/.zlocation.db"  If either is found, it uses that database, but if it needs to create a *new* database, it will name it ".zlocation.db"

**Comment by vors** [comment]
Yes, a little bit more migration logic! :D

**Comment by glucas** [comment]
Perhaps it could just be configurable.. e.g. check for $env:ZLOCATION_DB and fall back to default location.
