### ISSUE TITLE
Exception calling "Add" with "2" arguments

### ISSUE THREAD

**Issue by glucas** [vors/ZLocation#61]
Today I started getting an error when I try to jump to a location:

    Exception calling "Add" with "2" argument(s): "Item has already been added. Key in dictionary:     
    'C:\temp\foo'  Key being added: 'C:\Temp\foo'"
    At <....>\Modules\ZLocation\1.0.0\ZLocation.Storage.psm1:12 char:9
    +         $hash.add($item.path, $item.weight)

It looks like the case difference (C:\Temp vs C:\temp) may be causing an issue?

**Comment by glucas** [comment]
As a workaround, I used Remove-ZLocation to remove both variants of the path causing the problem,

**Comment by vors** [comment]
Oh interesting finding, thank you! We should fix it

**Comment by glucas** [comment]
My first thought is we don't want the same path stored multiple times with different case, so I'd probably look at changing Add-ZWeight to normalize the path somehow. 

Looks like this approach might work to normalize the case, both commands below result in the same "C:\Temp" result:

     (Get-Item C:\Temp).Target
     (Get-Item C:\temp).Target
