### ISSUE TITLE
Avoid assembly conflicts with other versions of LiteDB

### ISSUE THREAD

**Issue by cspotcode** [vors/ZLocation#74]
Creating this to track an issue I've noticed.  If another module loads a conflicting version of LiteDB, we might hit problems.  I'm not sure if there is a proper solution to this.  I've been playing around with creating a new `AssemblyLoadContext` to load LiteDB.dll.  This is apparently dotnet core's solution for isolating assemblies and loading conflicting versions in the same process.  So far it has been working for me.

```
class MyAssemblyLoadContext : Runtime.Loader.AssemblyLoadContext {
    [Reflection.Assembly] Load([Reflection.AssemblyName]$assemblyName) {
        return $null
    }
}

$myAssemblyLoadContext = [MyAssemblyLoadContext]::new()
$assembly = $myAssemblyLoadContext.LoadFromAssemblyPath([IO.Path]::Combine($PSScriptRoot, "LiteDB\LiteDB.dll"))
Function GetLiteDBType($name) {
    ForEach($t in $assembly.ExportedTypes) {
        if($t.name -eq $name) {
            return $t
        }
    }
}
$TAType = [psobject].Assembly.GetType('System.Management.Automation.TypeAccelerators')
$TAType::Add('accelerators', $TAType)
[accelerators]::Add('LDBQuery', (GetLiteDBType 'Query'))
[accelerators]::Add('LDBBsonValue', (GetLiteDBType 'BsonValue'))
[accelerators]::Add('LDBBsonDocument', (GetLiteDBType 'BsonDocument'))
[accelerators]::Add('LDBBsonId', (GetLiteDBType 'BsonIdAttribute'))
[accelerators]::Add('LDBBsonMapper', (GetLiteDBType 'BsonMapper'))
[accelerators]::Add('LDBLiteDatabase', (GetLiteDBType 'LiteDatabase'))
[accelerators]::Add('LDBLiteCollection', (GetLiteDBType 'LiteCollection`1'))
```

Type accelerators are, unfortunately, not scoped to a module, so we'd either have to give the type accelerators a more unique prefix or avoid them entirely.  I think `[$referenceToType]` syntax works.

**Comment by vors** [comment]
Oh, interesting workaround. This is an issue that all PowerShell modules needs to solve, so perhaps there is a more platform-level solution? @daxian-dbw does the custom AssemblyLoadContext seems like a reasonable workaround?

**Comment by daxian-dbw** [comment]
Not sure about the context here, but `AssemblyLoadContext` is the only possible solution for loading different versions of the same assembly into the same process.

**Comment by vors** [comment]
@daxian-dbw is it recommended to pre-emptively wrap all popular dependency dlls in their own AssemblyLoadContext to avoid possible problem with other modules? That seems like something that should be solve at the platform level.

**Comment by daxian-dbw** [comment]
I'm working on a RFC to support loading a module in a separate `AssemblyLoadContext`, by adding a `-Isolated` switch to `Import-Module`. Hopefully that would be a platform level solution to this common problem.

**Comment by vors** [comment]
Ah awesome, I'm looking forward to it.

@cspotcode I think we should not try to add any workarounds for specific modules unless there is a real user pain about it.
