### ISSUE TITLE
ZLocation fails to remember any directory.

### ISSUE THREAD

**Issue by Elderry** [vors/ZLocation#77]
I try to `cd`ed to some directories, then `z` to those directories and failed. Then I tried `Get-zLocation` and it gives me nothing.

zLocation version: 1.1
PowerShell version: 6.1.2
Windows version: Windows 10 Pro 1809, 17763.253

**Comment by vors** [comment]
can you share your `$function:prompt`? It should contain `Update-ZLocation $pwd`, it's altered to include it during the `Import-Module ZLocation`.

**Comment by Elderry** [comment]
@vors Now I know the cause, I have `Import-Module ZLocation` *Before* customizing my `prompt`, thus `Update-ZLocation $pwd` is never injected into my `prompt`. After moving it to the end of powershell profile, this problem is solved.

**Comment by Elderry** [comment]
Recommend to mention that in the document, and thanks for the help.
