### ISSUE TITLE
Z-location is not recording folders

### ISSUE THREAD

**Issue by abergs** [vors/ZLocation#78]
Problem: navigating to new folders (with cd) does not update the z db. 

I run powershell 5.1 but my computer is connected to an AD.. i'm wondering if the $HOME variable changing when disconnected from network might cause trouble.

**Comment by vors** [comment]
The update happens when you are executing command in a directory, not when you `cd` into one.

**Comment by abergs** [comment]
Aha! Would it be possible to add a command to like "z-add {weight}" to make sure my "dev" map get indexed and for example rank higher than "desktop" when doing "z de"?

**Comment by abergs** [comment]
Does not seem to trigger when running commands either:

![image](https://user-images.githubusercontent.com/357283/53733317-f5acf680-3e80-11e9-809a-2431a8786790.png)

**Comment by vors** [comment]
Oh is it cmder by any chance? I think there were some problems with it #45

**Comment by greenmooseSE** [comment]
FWIW, I struggled with this as well after upgrading to ```1.3.0``` and finally found out that I had, for whatever reason back in history, below line in my profile script:
```Import-Module ZLocation;```
Removing that solved it and Z-Location now records folders again.

**Comment by vors** [comment]
@greenmooseSE oh, fascinating. Do you mean that it was double-imported?

**Comment by ChristianSauer** [comment]
This is old, but yes this was also my problem - it was in my current $profile and $profile.CurrentUserAllHosts

**Comment by iansedano** [comment]
I ran into this problem too when upgrading to Powershell core from plain Windows Powershell. It seemed to be working but I later realized that it wasn't updating the folders visited.

It seems like with Powershell core ([actually it seems like from version 3.0](https://docs.microsoft.com/en-us/powershell/scripting/developer/module/importing-a-powershell-module?view=powershell-7.2#implicitly-importing-a-module-powershell-30)) you don't need to `Import-Module` anymore. That said, it was never a problem before Powershell Core (or at least v7 which I upgraded to).

I just removed any mention of `Import-Module` from any profile files and it started adding paths again.

Starting a new shell I tested to see whether it was being imported from anywhere else with `Get-Module` and it was not imported. However, upon sending just `z` as a command, it automatically imports it. Not sure why it seems to block updating the history when done explicitly via a profile.

**Comment by awdr74100** [comment]
I want to offer my own solution for those who need it. The documentation mentions putting `Import-Module ZLocation` after the Import of modules like posh-git, which also contains oh-my-posh and similar modules, as follows:

```pwsh
Import-Module -Name posh-git

oh-my-posh prompt init pwsh --config ~/.pwsh.omp.json | iex # download from scoop

Import-Module -Name ZLocation
```

It worked!

@iansedano's problem also happened to me, I think it might be that when calling the `z` command, the Module will be loaded as the last item, it will succeed anyway, and when `Import-Module ZLocation` is put in the wrong location, the asynchronous state may not be captured, I'm not sure that's the right description, please excuse my unfamiliarity with the language.

**Comment by pplmx** [comment]
> 

Works for me. Thanks a lot. Import should be after oh-my-posh init

**Comment by pplmx** [comment]
Occurred again ................ 😭

**Comment by expl0r3rgu1** [comment]
Tell me if I understood correctly: in order to record a directory I need to type `Update-ZLocation path/to/dir`. It doesn't automatically record and rank directories I cd in.
Right?

**Comment by MisinformedDNA** [comment]
@expl0r3rgu1 It _should_ record and rank the directories that you cd into.

**Comment by expl0r3rgu1** [comment]
> @expl0r3rgu1 It _should_ record and rank the directories that you cd into.

It should, but it doesn't as of today.

**Comment by MisinformedDNA** [comment]
> > @expl0r3rgu1 It _should_ record and rank the directories that you cd into.
> 
> It should, but it doesn't as of today.

It works fine for me now.

**Comment by bozho** [comment]
If you are explicitly importing the module in your profile file, make sure you're importing it after any other modules/utilities that alter the prompt (e.g. oh-my-posh).

**Comment by abergs** [comment]
Multiple solutions posted here, I think a @bozho was the one that worked for me back in the day. Closing.
