### ISSUE TITLE
Invoke-Zlocation doesn't call Set-ZLocation correctely

### ISSUE THREAD

**Issue by adamlopresto** [vors/ZLocation#79]
Took me forever to figure this out, but it seems that on my system, "Invoke-ZLocation" if passed multiple parameters forced them to flatten before calling "Set-ZLocation". Changing line 288 of ZLocation.psm1 from

    Set-ZLocation $match

to 

    Set-ZLocation -match $match

Fixed the issue for me.

**Comment by vors** [comment]
Oh nice catch!
Can you, please, elaborate about the scenario that was broken?

All would you be up to send a pull request with this simple fix? I want people to get credit for their fixes in git history. If you need help with contributing to github project, I'd be glad to walk you thru the process.

**Comment by adamlopresto** [comment]
I've attempted to create a pull request. https://github.com/vors/ZLocation/pull/82
I also tried to document the issue that it was causing in the request (good practice anyway). This is actually my first pull request, so please let me know if there are any problems with it.
