### ISSUE TITLE
[Feature Request] Expose tab-completion related commands/functions

### ISSUE THREAD

**Issue by devkabiir** [vors/ZLocation#89]
Hi, I am new to PowerShell, Thank you for such an amazing Module!

I have been using it for quite some time now, and I thought it could be good for my workflow if I could auto-complete directories in other commands too.

If tab-completion related commands were exported/exposed, then it would greatly improve my workflow and possibly for other users as well.

Example
`code <tab>` would auto-complete the most used one and I can directly open that in my code editor

`explorer mobile<tab>` would auto-complete the most used directory with mobile in it and I can open that in explorer.

This would require me to `Register-ArgumentCompleter` for `code` and `explorer` commands. But I can't do that without the required commands from ZLocation.

The required commands are `Find-Matches` and `Get-ZLocation`

If there is a way for me to use those commands without you exporting/exposing them, please tell me. Currently I am trying to do it this way `Import-Module <path-to-modules>/ZLocation/<version>/<required-but-private-module-name>.psm1`.

**Comment by vors** [comment]
Hey, thank you for the kind words, glad that you find it useful!

One easy workaround about how to call private functions from any PowerShell module is the following syntax `& $m {...}` - invoke scriptblock in the context of the module `$m`. For example

```
$m = Get-Module ZLocation
$query = 'se'                                                          
& $m {Find-Matches (Get-ZLocation) $query | & $m Get-EscapedPath } 
```

I hope that would help you build the native completers. There are native completers examples available here https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/register-argumentcompleter?view=powershell-6

**Comment by devkabiir** [comment]
Hi, I tried this today, thanks for the tip.

Here is a working example for anyone who is looking for it

```powershell
if (Get-Command -Name Register-ArgumentCompleter -ErrorAction Ignore) {
 
    Register-ArgumentCompleter -CommandName 'Invoke-ExplorerZ' -ParameterName 'match' -ScriptBlock {
        param($commandName, $parameterName, $wordToComplete, $commandAst, $fakeBoundParameter)
        # Omit first item (command name) and empty strings
        $i = $commandAst.CommandElements.Count
        [string[]]$query = if ($i -gt 1) {
            $commandAst.CommandElements[1..($i - 1)] | ForEach-Object { $_.toString() }
        }
        $m = Get-Module ZLocation
        & $m { param($query) Find-Matches (Get-ZLocation) $query | Get-EscapedPath } -ArgumentList $query
    }
}



function Invoke-ExplorerZ {
    param(
        [Parameter(ValueFromRemainingArguments, ValueFromPipeline = $true, Position = 0)][Object[]]$match
    )

    if ($null -eq $match) {
        explorer.exe $pwd
        return
    }

    $match | ForEach-Object { explorer.exe $_ }
}

Set-Alias -Name e -Value Invoke-ExplorerZ
```

You can now open directories in explore with tab completions

```shell
e <tab>
e C:\my-directory
```

**Comment by vors** [comment]
Awesome!
