### ISSUE TITLE
When have an exact name match, prefer it over stronger weighted but partial match

### ISSUE THREAD

**Issue by scottbilas** [vors/ZLocation#90]
My db contains this:

   285 C:\work\dots
   310 C:\work\dots2
   ...

But when I go to "dots" it selects "dots2" because it has higher weight.

I expect that if I type in a folder name that matches exactly, it would select that one rather than something else that has a higher weight, but is a partial match.

**Comment by vors** [comment]
yes good point - it annoyed me a lot too.

**Comment by vors** [comment]
Ok published 1.3.0 with a fix for it, please update from the gallery.

**Comment by scottbilas** [comment]
Confirmed fixed, thanks!
